<?php

/**
 * Provide a admin area view for the plugin
 *
 * This file is used to markup the admin-facing aspects of the plugin. It is the
 * scaffolding template partial generated by the WordPress Plugin Boilerplate;
 * it is intended to be included by the admin class and to hold the HTML for an
 * admin screen. Currently it ships as a placeholder with no active markup.
 *
 * @link       http://wpstream.net
 * @since      3.0.1
 *
 * @package    Wpstream
 * @subpackage Wpstream/admin/partials
 */
?>

<!-- This file should primarily consist of HTML with a little bit of PHP. -->
